# Allow externalization of properties using application-ext.properties
spring.profiles.active=ext

# Database Configuration - PostgreSQL
spring.datasource.url=${NEXTSTEP_DATASOURCE_URL}
spring.datasource.username=${NEXTSTEP_DATASOURCE_USERNAME:}
spring.datasource.password=${NEXTSTEP_DATASOURCE_PASSWORD:}

# Data Adapter Server Service URL
powerauth.dataAdapter.service.url=${NEXTSTEP_DATA_ADAPTER_URL}

# PowerAuth Server URL
powerauth.service.url=${NEXTSTEP_POWERAUTH_SERVICE_URL}

# PowerAuth Server Service Security Settings
powerauth.service.security.clientToken=${NEXTSTEP_POWERAUTH_SECURITY_TOKEN:}
powerauth.service.security.clientSecret=${NEXTSTEP_POWERAUTH_SECURITY_SECRET:}
powerauth.service.ssl.acceptInvalidSslCertificate=${NEXTSTEP_ACCEPT_INVALID_SSL_CERTIFICATE:false}
powerauth.nextstep.security.auth.type=${NEXTSTEP_AUTH_TYPE:NONE}
spring.security.oauth2.resource-server.jwt.issuer-uri=${NEXTSTEP_SECURITY_AUTH_OIDC_ISSUER_URI:}
spring.security.oauth2.resource-server.jwt.audiences=${NEXTSTEP_SECURITY_AUTH_OIDC_AUDIENCES:}


spring.datasource.driver-class-name=${NEXTSTEP_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=${NEXTSTEP_JPA_DDL_AUTO:none}

# Configuration of Database Charset
spring.jpa.properties.hibernate.connection.CharSet=${NEXTSTEP_JPA_CHARSET:UTF-8}
spring.jpa.properties.hibernate.connection.characterEncoding=${NEXTSTEP_JPA_CHARACTER_ENCODING:UTF-8}
spring.jpa.properties.hibernate.connection.useUnicode=${NEXTSTEP_JPA_USE_UNICODE:true}

# Additional JPA Configuration
spring.jpa.database-platform=${NEXTSTEP_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# Operation Expiration Time in Seconds
powerauth.nextstep.operation.expirationTimeInSeconds=${NEXTSTEP_OPERATION_EXPIRATION_TIME:300}

# PowerAuth Operations Settings
powerauth.nextstep.pa.operations.enabled=${NEXTSTEP_POWERAUTH_OPERATIONS_ENABLED:false}

# Encryption Settings
powerauth.nextstep.e2eEncryption.key=${NEXTSTEP_E2E_ENCRYPTION_KEY:}
powerauth.nextstep.db.master.encryption.key=${NEXTSTEP_MASTER_DB_ENCRYPTION_KEY:}

# Database Configuration - JNDI
spring.datasource.jndi-name=${NEXTSTEP_DATASOURCE_JNDI_NAME:false}

# JMX Configuration
spring.jmx.enabled=${NEXTSTEP_SPRING_JMX_ENABLED:false}
spring.jmx.default-domain=${NEXTSTEP_SPRING_JMX_DEFAULT_DOMAIN:powerauth-nextstep}

# Application Configuration
powerauth.nextstep.service.applicationName=${NEXTSTEP_APPLICATION_NAME:powerauth-nextstep}
powerauth.nextstep.service.applicationDisplayName=${NEXTSTEP_APPLICATION_DISPLAY_NAME:PowerAuth Next Step Server}
powerauth.nextstep.service.applicationEnvironment=${NEXTSTEP_APPLICATION_ENVIRONMENT:}

# Custom Logging Configuration
logging.config=${NEXTSTEP_LOGGING:}