# Allow externalization of properties using application-ext.properties
spring.profiles.active=ext

# Database Configuration - PostgreSQL
spring.datasource.url=${NEXTSTEP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/powerauth}
spring.datasource.username=${NEXTSTEP_DATASOURCE_USERNAME:powerauth}
spring.datasource.password=${NEXTSTEP_DATASOURCE_PASSWORD:}
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.pool-name=HikariPool-NextStep
spring.jpa.properties.hibernate.connection.CharSet=${NEXTSTEP_JPA_CHARSET:UTF-8}
spring.jpa.properties.hibernate.connection.characterEncoding=${NEXTSTEP_JPA_CHARACTER_ENCODING:utf8}
spring.jpa.properties.hibernate.connection.useUnicode=${NEXTSTEP_JPA_USE_UNICODE:true}
spring.jpa.hibernate.ddl-auto=${NEXTSTEP_JPA_DDL_AUTO:none}
spring.datasource.jndi-name=${NEXTSTEP_DATASOURCE_JNDI_NAME:false}

# Database Configuration - Oracle
#spring.datasource.url=${NEXTSTEP_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/powerauth}
#spring.datasource.username=powerauth
#spring.datasource.password=

# Data Adapter Server Service URL
powerauth.dataAdapter.service.url=${NEXTSTEP_DATA_ADAPTER_URL:http://localhost:8080/powerauth-data-adapter}

# PowerAuth Server URL
powerauth.service.url=${NEXTSTEP_POWERAUTH_SERVICE_URL:http://localhost:8080/powerauth-java-server/rest}
powerauth.service.restClientConfig.responseTimeout=60s
powerauth.service.restClientConfig.maxIdleTime=200s
powerauth.service.security.clientToken=${NEXTSTEP_POWERAUTH_SECURITY_TOKEN:}
powerauth.service.security.clientSecret=${NEXTSTEP_POWERAUTH_SECURITY_SECRET:}
# Whether invalid SSL certificates should be accepted
powerauth.service.ssl.acceptInvalidSslCertificate=${NEXTSTEP_ACCEPT_INVALID_SSL_CERTIFICATE:false}

# Operation expiration time in seconds
powerauth.nextstep.operation.expirationTimeInSeconds=${NEXTSTEP_OPERATION_EXPIRATION_TIME:300}

# Use original username for a removed credential when the credential is recreated
powerauth.nextstep.identity.credential.useOriginalUsername=false

# Maximum number of attempts when generating username
powerauth.nextstep.identity.credential.generateUsernameMaxAttempts=100

# Enable or disable operations support in PowerAuth server
powerauth.nextstep.pa.operations.enabled=${NEXTSTEP_POWERAUTH_OPERATIONS_ENABLED:false}

# Key used for end-to-end encryption of credentials
powerauth.nextstep.e2eEncryption.key=${NEXTSTEP_E2E_ENCRYPTION_KEY:}

# Key used for database record encryption
powerauth.nextstep.db.master.encryption.key=${NEXTSTEP_MASTER_DB_ENCRYPTION_KEY:}

# Application Service Configuration
powerauth.nextstep.service.applicationName=${NEXTSTEP_APPLICATION_NAME:powerauth-nextstep}
powerauth.nextstep.service.applicationDisplayName=${NEXTSTEP_APPLICATION_DISPLAY_NAME:PowerAuth Next Step Server}
powerauth.nextstep.service.applicationEnvironment=${NEXTSTEP_APPLICATION_ENVIRONMENT:}

# Set JMX default domain in case JMX is enabled, otherwise the application startup fails due to clash in JMX bean names
spring.jmx.default-domain=${NEXTSTEP_SPRING_JMX_DEFAULT_DOMAIN:powerauth-nextstep}
spring.jmx.enabled=${NEXTSTEP_SPRING_JMX_ENABLED:false}

# Set Jackson date format
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ

# Disable open session in view to avoid startup warning of Spring boot
spring.jpa.open-in-view=false

# Disable swagger-ui default petstore url
springdoc.swagger-ui.disable-swagger-default-url=true

# Set default media type for responses in REST API documentation
springdoc.default-produces-media-type=application/json

# Set the Spring application name
spring.application.name=powerauth-nextstep

banner.application.name=${spring.application.name}
banner.application.version=@project.version@

logging.config=${NEXTSTEP_LOGGING:}

# OpenID Connect (OIDC) Settings
powerauth.nextstep.security.auth.type=${NEXTSTEP_AUTH_TYPE:NONE}
spring.security.oauth2.resource-server.jwt.issuer-uri=${NEXTSTEP_SECURITY_AUTH_OIDC_ISSUER_URI:}
spring.security.oauth2.resource-server.jwt.audiences=${NEXTSTEP_SECURITY_AUTH_OIDC_AUDIENCES:}

# Monitoring
management.tracing.sampling.probability=1.0


# LDAP
powerauth.nextstep.ldap.enabled=${NEXTSTEP_LDAP_ENABLED:false}
powerauth.nextstep.ldap.url=${NEXTSTEP_LDAP_URL:}
powerauth.nextstep.ldap.base=${NEXTSTEP_LDAP_BASE:}
powerauth.nextstep.ldap.managerDn=${NEXTSTEP_LDAP_MANAGERDN:}
powerauth.nextstep.ldap.managerPassword=${NEXTSTEP_LDAP_MANAGERPASSWORD:}
powerauth.nextstep.ldap.anonymousReadOnly=${NEXTSTEP_LDAP_ANONYMOUSREADONLY:false}
powerauth.nextstep.ldap.userSearchBase=${NEXTSTEP_LDAP_USERSEARCHBASE:ou=People}
powerauth.nextstep.ldap.userSearchFilter=${NEXTSTEP_LDAP_USERSEARCHFILTER:(uid={0})}
powerauth.nextstep.ldap.connectTimeout=${NEXTSTEP_LDAP_CONNECTTIMEOUT:5000}
powerauth.nextstep.ldap.readTimeout=${NEXTSTEP_LDAP_READTIMEOUT:5000}

spring.autoconfigure.exclude=\
  org.springframework.boot.actuate.autoconfigure.metrics.jersey.JerseyServerMetricsAutoConfiguration, \
  org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
