name: Package with Maven and JDK 8

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/wultra/server_jdk_8_ubuntu:u202
    steps:
      - uses: actions/checkout@v3
      - run: mvn --batch-mode package
      - run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
