name: Build and Publish docker image

on:
  workflow_dispatch:
    inputs:
      push_to_registry:
        type: boolean
        default: false
        description: Publish to registry?
      environment:
        type: environment
        default: docker-internal
        description: Select the environment
      products_to_build:
        description: Array of product names for which build will be done.
        type: string
        default: '["nextstep"]'
        required: true

  pull_request:
    branches:
      - 'develop'
      - 'releases/*'
    paths:
      - '**'
      - '!docs/**'
      - '!doc-private/**'
      - 'docs/db/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish-docker-image:
    uses: wultra/wultra-infrastructure/.github/workflows/build-publish-docker-image.yml@issues/add-general-docker-workflow
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      push_to_registry: ${{ inputs.push_to_registry }}
      products_to_build_and_push: ${{ inputs.products_to_build_and_push }} || '["nextstep"]'