name: Run SCP deploy

on:
  workflow_dispatch:

jobs:
  scp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print directory
        shell: bash
        run: |
          ll
      - name: print path
        shell: bash
        run: |
          pwd
